[unstable]
codegen-backend = true

[profile.dev]
codegen-backend = "cranelift"

[profile.dev.package."*"]
codegen-backend = "llvm"

[target.x86_64-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld",
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y",
]

# for Windows
[target.x86_64-pc-windows-msvc]
rustflags = [
    # (Nightly) Make the current crate share its generic instantiations
    "-Zshare-generics=y"
]
